import {
    IconAlertTriangle,
    IconArrowRight,
    IconCheck,
    IconChevronLeft,
    IconChevronRight,
    IconCommand,
    IconCreditCard,
    IconFile,
    IconFileText,
    IconHelpCircle,
    IconPhoto,
    IconDeviceLaptop,
    IconLayoutDashboard,
    IconLoader2,
    IconLogin,
    IconProps,
    IconShoppingBag,
    IconMoon,
    IconDotsVertical,
    IconPizza,
    IconPlus,
    IconSettings,
    IconSun,
    IconTrash,
    IconBrandTwitter,
    IconUser,
    IconUserCircle,
    IconUserEdit,
    IconUserX,
    IconX,
    IconLayoutKanban,
    IconBrandGithub,
    IconPackageExport,
    IconPackages,
    IconTruckDelivery,
    IconWallet,
    IconBuildingBank,
    IconCash,
    IconDeviceMobile,
    IconClockHour4,
    IconReportMoney,
} from '@tabler/icons-react';

import {
    Boxes,
    Factory,
    Wrench,
    Tag,
    PlusSquare,
    TrendingUp,
    ArrowUpRight,
    Badge,
    Shapes
} from "lucide-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
    creditCard: IconCreditCard,
    wallet: IconWallet,
    bank: IconBuildingBank,
    cash: IconCash,
    upi: IconDeviceMobile,
    emi: IconReportMoney,
    paylater: IconClockHour4,
    shipment: IconPackageExport,       // 📦 generic shipment
    allShipments: IconPackages,        // 📦📦 all shipments
    shipmentDetails: IconTruckDelivery, // 🚚 details by ID
    dashboard: IconLayoutDashboard,
    logo: IconCommand,
    login: IconLogin,
    close: IconX,
    product: IconShoppingBag,
    spinner: IconLoader2,
    kanban: IconLayoutKanban,
    chevronLeft: IconChevronLeft,
    chevronRight: IconChevronRight,
    trash: IconTrash,
    employee: IconUserX,
    post: IconFileText,
    page: IconFile,
    userPen: IconUserEdit,
    user2: IconUserCircle,
    media: IconPhoto,
    settings: IconSettings,
    billing: IconCreditCard,
    ellipsis: IconDotsVertical,
    add: IconPlus,
    warning: IconAlertTriangle,
    user: IconUser,
    arrowRight: IconArrowRight,
    help: IconHelpCircle,
    pizza: IconPizza,
    sun: IconSun,
    moon: IconMoon,
    laptop: IconDeviceLaptop,
    github: IconBrandGithub,
    twitter: IconBrandTwitter,
    check: IconCheck,
    Boxes,
    Factory,
    Wrench,
    Tag,
    PlusSquare,
    TrendingUp,
    ArrowUpRight,
    Badge,
    Shapes
};

