import { AppShell } from "@/components/layout/app-shell";
import { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by GK EV",
};
export default function DashboardLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <AppShell>
            {children}
            <Toaster />
        </AppShell>
    )
}