import { Metadata } from "next";
import KBar from '@/components/kbar';
import { cookies } from 'next/headers';
import { InfobarProvider } from "@/components/ui/infobar";
import { InfoSidebar } from "@/components/layout/info-sidebar";
import AppSidebar from "@/components/layout/app-sidebar";
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import Header from "@/components/layout/header";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by GK EV",
};


export default async function DashboardLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true';
    return (
        <KBar>
            <TooltipProvider>
                <SidebarProvider defaultOpen={defaultOpen}>
                    <AppSidebar />
                    <SidebarInset>
                        <Header />
                        <InfobarProvider defaultOpen={false}>
                            {children}
                            <InfoSidebar side='right' />
                        </InfobarProvider>
                    </SidebarInset>
                </SidebarProvider>
            </TooltipProvider>
        </KBar>
    )
}