import { AppShell } from "@/components/layout/app-shell";
import { Metadata, Viewport } from "next";
import { Toaster } from "@/components/ui/sonner";
import Providers from '@/components/layout/providers';
import ThemeProvider from '@/components/layout/ThemeToggle/theme-provider';
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";

const META_THEME_COLORS = {
    light: '#ffffff',
    dark: '#09090b'
};
export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by GK EV",
};
export const viewport: Viewport = {
    themeColor: META_THEME_COLORS.light
};

export default async function DashboardLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const cookieStore = await cookies();
    const activeThemeValue = cookieStore.get('active_theme')?.value;
    const isScaled = activeThemeValue?.endsWith('-scaled');

    return (
        <html lang='en' suppressHydrationWarning>
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
              try {
                if (localStorage.theme === 'dark' || ((!('theme' in localStorage) || localStorage.theme === 'system') && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.querySelector('meta[name="theme-color"]').setAttribute('content', '${META_THEME_COLORS.dark}')
                }
              } catch (_) {}
            `
                    }}
                />
            </head>
            <body
                className={cn(
                    'bg-background overflow-hidden overscroll-none font-sans antialiased',
                    activeThemeValue ? `theme-${activeThemeValue}` : '',
                    isScaled ? 'theme-scaled' : '',

                )}
            >
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                    enableColorScheme
                >
                    <Providers activeThemeValue={activeThemeValue as string}>
                        <Toaster />
                        <AppShell>
                            {children}
                        </AppShell>
                    </Providers>
                </ThemeProvider>
            </body>
        </html>
    )
}